=== Simulacr/warufuzake/Nihongo/src/main/webapp/resources/nihongo/test/total/adposition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="adposition" type="adpositionType"/>
  <xs:complexType name="adpositionType">
    <xs:sequence>
      <xs:element type="reiType" name="rei"/>
      <xs:element type="mondaiType" name="mondai"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="kanjiType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="furi" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="mondaiType" mixed="true">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="kanjiType" name="kanji"/>
      <xs:element name="shitsumon">
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="reiType" mixed="true">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="kanjiType" name="kanji"/>
      <xs:element name="example">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute type="xs:string" name="furi" use="optional"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
</xs:schema>

=== Simulacr/warufuzake/Nihongo/src/main/webapp/resources/nihongo/test/total/35/setchishi.xml
<?xml version="1.0" encoding="utf-8"?>
<adposition xmlns="http://www.w3schools.com/adposition"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.w3schools.com/adposition.xsd">

    <rei>
        <kanji furi="みち">道</kanji>
        <example>で</example>
        <kanji furi="さいふ">財布</kanji>
        <example>を</example>
        <kanji furi="ひろ">拾</kanji>いました。
    </rei>
    <mondai>
        <kanji furi="みち">予定</kanji>
        <shitsumon>が</shitsumon>
        <kanji furi="みち">変</kanji>わったら、
        <kanji furi="みち">連絡</kanji>してください。
    </mondai>
</adposition>
